topics:
  /livox/lidar_192_168_100_116: sensor_msgs/msg/PointCloud2
  /livox/lidar_192_168_100_115: sensor_msgs/msg/PointCloud2
  /top_os/points: sensor_msgs/msg/PointCloud2
  /front_os/points: sensor_msgs/msg/PointCloud2
  /front_camera/rgb/image_raw: sensor_msgs/msg/Image
  /rear_camera/rgb/image_raw: sensor_msgs/msg/Image
